config/routes.rb
Rails.application.routes.draw do
  resources :professors, except: [:index] do
    collection do
      get 'login'
    end
  end
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :students
  resources :projects do
    member do
      get :take
      get :drop
    end
  end

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

  has_one :project, dependent: :nullify

  validates_uniqueness_of :email
  validates_presence_of :name, :email
  has_secure_password

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]
  before_action :authorize_professor, only: [:index]
  before_action :authorize_professor_or_current_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        session[:student_id] = @student.id
        format.html { redirect_to '/', notice: 'Sign up successful' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    session[:student_id] = nil
    respond_to do |format|
      format.html { redirect_to login_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authorize_professor_or_current_student
      raise ActionController::RoutingError.new('Not Found') unless professor_or_current_student?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :password, :password_confirmation)
    end

    def professor_or_current_student?
      current_professor.present? || current_student_matches_id?
    end
    helper_method :professor_or_current_student?

    def current_student_matches_id?
      current_student.present? && current_student.id.to_s == params[:id]
    end
end

app/helpers/students_helper.rb
module StudentsHelper
  def professor_or_current_student?
    current_professor.present? || current_student_matches_id?
  end

  private

  def current_student_matches_id?
    current_student.present? && current_student.id.to_s == params[:id]
  end
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <% if current_student.present? %>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% else %>
      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1 class="row">Editing Student</h1>
<div class="row">
  <%= render 'form', student: @student %>
</div>
<br>
<div class="row">
  <%= link_to 'Cancel', @student %>
  | <%= link_to 'Delete account', @student, method: :delete,
          data: { confirm: "This will delete your account, and remove you from projects. Are you sure?" }  %>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>Student Sign Up!</h1>

<div class="row">
  <%= render 'form', student: @student %>
</div>
<br>
<div class="row">
  <%= link_to 'Login', '/login' %>
  | <%= link_to 'Professor sign up' %>
</div>

app/views/students/show.html.erb
<div class="row">
  <h1>Student</h1>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @student.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @student.email %>
  </p>
</div>

<% if professor_or_current_student? %>
  <div class="row">
    <%= link_to 'Edit', edit_student_path(@student) %>
    | <%= link_to 'Delete account', @student, method: :delete,
            data: { confirm: "This will delete your account, and remove you from projects. Are you sure?" }  %>
  </div>
<% end %>