config/routes.rb
Rails.application.routes.draw do
  resources :professors, except: [:index] do
    collection do
      get 'login'
    end
  end
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :students
  resources :projects do
    member do
      get :take
      get :drop
    end
  end

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord

  validates_uniqueness_of :email
  validates_presence_of :email, :name
  has_secure_password
  has_many :projects, dependent: :destroy

end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  before_action :authorize_professor, only: [:edit, :update, :destroy]
  before_action :authorize_current_professor, only: [:edit, :update, :destroy]

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        session[:professor_id] = @professor.id
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /professors/login
  def login
    @professor_login = true
    render "sessions/new"
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    session[:professor_id] = nil
    respond_to do |format|
      format.html { redirect_to login_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authorize_current_professor
      raise ActionController::RoutingError.new('Not Found') unless params[:id] == current_professor.id.to_s
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(professor) do |f| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/new.html.erb
<h1>Professor Sign Up!</h1>

<div class="row">
  <%= render 'form', professor: @professor %>
</div>
<br>
<div class="row">
  <%= link_to 'Login', login_professors_path %>
  | <%= link_to 'Student sign up', new_student_path %>
</div>

app/views/professors/show.html.erb
<div class="row">
  <h1>Professor</h1>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @professor.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @professor.email %>
  </p>
</div>

<% if session[:professor_id] == @professor.id %>
  <div class="row">
    <%= link_to 'Edit', edit_professor_path(@professor) %>
    | <%= link_to 'Delete account', professor_path(@professor), method: :delete,
            data: { confirm: "This will delete your account, and all projects. Are you sure?" }  %>
  </div>
<% end %>