config/routes.rb
Rails.application.routes.draw do
  resources :professors, except: [:index] do
    collection do
      get 'login'
    end
  end
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :students
  resources :projects do
    member do
      get :take
      get :drop
    end
  end

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :professor
  belongs_to :student, optional: true
  validate :student_cannot_null_if_updating_student, on: :update
  validates :student, uniqueness: { message: 'already has a project, drop that before taking another one.' }, if: 'student.present?'


  def student_cannot_null_if_updating_student
    if student_id_changed? && student_id_was.present? && student_id.present?
      errors.add(:student_id, 'has already taken this project, please choose another project')
    end
  end
end

app/controllers/projects_controller.rb
 class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :take, :drop]
  before_action :authorize, except: [:show, :index]
  before_action :authorize_student, only: [:take, :drop]
  before_action :authorize_student_project, only: [:drop]
  before_action :authorize_professor, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize_professor_project, only: [ :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /projects/1/take
  # GET /projects/1/take.json
  def take
    respond_to do |format|
      if @project.update(student: current_student)
        format.html { redirect_to @project, notice: 'Project was successfully taken.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { redirect_to @project, flash: { error: @project.errors.full_messages.join("<br/>") } }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /projects/1/drop
  # GET /projects/1/drop.json
  def drop
    respond_to do |format|
      if @project.update(student: nil)
        format.html { redirect_to @project, notice: 'Project was successfully dropped.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { redirect_to @project, flash: { error: @project.errors.full_messages.join("<br/>") } }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def authorize_professor_project
      raise ActionController::RoutingError, 'Not Found' if current_professor.id != @project.professor_id
    end

    def authorize_student_project
      raise ActionController::RoutingError, 'Not Found' if current_student.id != @project.student_id
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :publish_at).merge(professor_id: current_professor.id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :publish_at %>
    <%= f.datetime_field :publish_at, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Atrributed</th>
      <% if current_professor.present? %>
        <th colspan="3"></th>
      <% else %>
        <th clospan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.student.try(:name) || "Unattributed" %></td>
        <td><%= link_to 'Show', project %></td>
        <% if current_professor.present? && current_professor.id == project.professor_id %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_professor.present? %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<br/>
<p id="notice"><%= notice %></p>
<p class="text-danger">
  <%= flash[:error] %>
</p>

<div class="card">
  <div class="card-header">
    <%= @project.title %>
  </div>
  <div class="card-block">
    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>

    <p>
      <strong>Available at:</strong>
      <%= @project.publish_at %>
    </p>

    <p>
      <strong>Attributed to: </strong>
      <%= @project.student.try(:name) || "Unattributed" %>
    </p>
  </div>
</div>

<% if current_student.present? %>
  <% if @project.student_id.nil? && current_student.project.nil? %>
    <%= link_to 'Take Project', take_project_path(@project) %> |
  <% elsif @project.student_id == current_student.id %>
    <%= link_to 'Drop Project', drop_project_path(@project) %> |
  <% end %>
<% elsif current_professor.present? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>